name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 8 * * 1-6'  # Every day from Monday to Saturday at 08:00 UTC
    - cron: '0 11 * * 0'   # Every Sunday at 11:00 UTC

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build and run parser
      run: go run ./parser.go

    - name: Publish UI artifact
      uses: actions/upload-artifact@v4
      with:
        name: ui-generated
        path: index.html
        if-no-files-found: error

    - name: Check for changes in statuses.json
      id: check_changes
      run: |
        git diff --exit-code --quiet statuses.json || echo "::set-output name=changed::true"
        git diff --exit-code --quiet rt_statuses.json || echo "::set-output name=changed_rt::true"

    - name: Commit and push changes to statuses.json
      if: steps.check_changes.outputs.changed == 'true' || steps.check_changes.outputs.changed_rt == 'true'
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add statuses.json rt_statuses.json
        git commit -m "Update statuses.json and rt_statuses.json [skip ci]"
        git push

  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
      pages: write
      id-token: write
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Download UI artifact
      uses: actions/download-artifact@v4
      with:
        name: ui-generated
        path: .

    - name: Configure GitHub Pages
      uses: actions/configure-pages@v1

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: .

    - id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
